server:
  port: 8081

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: 人员档案服务

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    com.tik.aipusharchiveservice.dal.mapper: debug
    com.tik.aipusharchiveservice: info
    com.alibaba.nacos: info

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-runtime-dialect: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
